export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';

export const SET_REDIRECT_TO_CURRENT_WEATHER = 'SET_REDIRECT_TO_CURRENT_WEATHER';

export const FETCH_CURRENT_WEATHER_START = 'FETCH_CURRENT_WEATHER_START';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_CURRENT_WEATHER_FAIL = 'FETCH_CURRENT_WEATHER_FAIL';

export const FETCH_FORECAST_WEATHER_START = 'FETCH_FORECAST_WEATHER_START';
export const FETCH_FORECAST_WEATHER_SUCCESS = 'FETCH_FORECAST_WEATHER_SUCCESS';
export const FETCH_FORECAST_WEATHER_FAIL = 'FETCH_FORECAST_WEATHER_FAIL';

export const FETCH_LOCATIONS_BY_PREFIX_START = 'FETCH_LOCATIONS_BY_PREFIX_START';
export const FETCH_LOCATIONS_BY_PREFIX_SUCCESS = 'FETCH_LOCATIONS_BY_PREFIX_SUCCESS';
export const FETCH_LOCATIONS_BY_PREFIX_FAIL = 'FETCH_LOCATIONS_BY_PREFIX_FAIL';

export const FETCH_LOCATION_BY_COORDS_START = 'FETCH_LOCATION_BY_COORDS_START';
export const FETCH_LOCATION_BY_COORDS_SUCCESS = 'FETCH_LOCATION_BY_COORDS_SUCCESS';
export const FETCH_LOCATION_BY_COORDS_FAIL = 'FETCH_LOCATION_BY_COORDS_FAIL';