export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';

export const ADD_LOCATION = 'ADD_LOCATION';
export const SET_HIGHLIGHTED_LOCATION = 'SET_HIGHLIGHTED_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';

export const SET_LOCATIONS = 'SET_LOCATIONS';

export const FETCH_CURRENT_WEATHER_START = 'FETCH_CURRENT_WEATHER_START';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_CURRENT_WEATHER_FAIL = 'FETCH_CURRENT_WEATHER_FAIL';

export const FETCH_FORECAST_WEATHER_START = 'FETCH_FORECAST_WEATHER_START';
export const FETCH_FORECAST_WEATHER_SUCCESS = 'FETCH_FORECAST_WEATHER_SUCCESS';
export const FETCH_FORECAST_WEATHER_FAIL = 'FETCH_FORECAST_WEATHER_FAIL';

export const REFRESH_FORECAST_WEATHER_START = 'REFRESH_FORECAST_WEATHER_START';
export const REFRESH_FORECAST_WEATHER_SUCCESS = 'REFRESH_FORECAST_WEATHER_SUCCESS';
export const REFRESH_FORECAST_WEATHER_FAIL = 'REFRESH_FORECAST_WEATHER_FAIL';

export const FETCH_LOCATIONS_BY_PREFIX_START = 'FETCH_LOCATIONS_BY_PREFIX_START';
export const FETCH_LOCATIONS_BY_PREFIX_SUCCESS = 'FETCH_LOCATIONS_BY_PREFIX_SUCCESS';
export const FETCH_LOCATIONS_BY_PREFIX_FAIL = 'FETCH_LOCATIONS_BY_PREFIX_FAIL';